### ISSUE TITLE
ActionRunner - block on inbound jobs instead of sleep

### ISSUE THREAD

**Issue by scottyeager** [freeflowuniverse/baobab#13]
[Here](https://github.com/freeflowuniverse/baobab/blob/9b8fffa27c4090fc5fa1995752019bcd1f6e048d/baobab/actionrunner/actionrunner.v#LL36C39-L36C39) the ActionRunner polls for new jobs with timeout 0, then proceeds to sleep before checking again. I think it's better to provide a (long) timeout and remove the sleep.

Perhaps better yet would be to block indefinitely on input from Redis. This is [supported](https://redis.io/commands/blpop/) in the BRPOP/BLPOP operation when the timeout passed is 0, but baobab currently [interprets](https://github.com/freeflowuniverse/baobab/blob/9b8fffa27c4090fc5fa1995752019bcd1f6e048d/baobab/client/jobs_process.v#L19) timeout of 0 as non blocking.

**Comment by brandonpille** [comment]
Yes that could be an option. But.. There are a couple of issues that block me from doing that:

- We have multiple actors. That for loop is looping over all of them and executes jobs that are in the queue. We could create a new thread for each of the actors though that might introduce concurrency issues. 
- We want to be able to properly stop the server when we want to. This for loop allows us to do that. 
- The processor also has a for loop and it is handeling multiple queues also. I'm not sure if we can do those concurrently.

If it's worth it I can test a few things..

**Comment by brandonpille** [comment]
I fear that it will not be a good solution. I tried creating a thread for each queue that we handle in processor so that we can just brpop. Executing the tests take 2 x longer.

**Comment by scottyeager** [comment]
Ah, I missed the part where there are multiple queues in play.

BRPOP can take multiple keys to query, which should allow a blocking call that returns when an item becomes available on any of the queues. This would require adding support for multiple keys upstream in crystallib's redis implementation.

If this approach is valid, I do think it's worth the effort to implement. For the use case of farmerbot the current implementation is okay, but for a general purpose solution it would be much better to not build in a tradeoff between responsiveness and efficiency.

**Comment by despiegk** [comment]
doing multiple keys to query in crystal lib can be implemented in <1h, worth trying

**Comment by brandonpille** [comment]
I'll look into it today

**Comment by brandonpille** [comment]
Alright I implemented the changes in crystallib and baobab is using those. I'm going to run some tests on the farmerbot to see the cpu usage.

**Comment by brandonpille** [comment]
I tested it in the farmerbot. It's working fine. CPU usage is 0% when doing nothing. @scottyeager I added you as a reviewer too.
