### ISSUE TITLE
add info about actionrunner, processor to manual and v from proper documentation

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/baobab#15]
- how it works
- which objects to use, what goes on queue, how does it work
- link to v docs where relevant

**Comment by despiegk** [comment]
v docu is on https://freeflowuniverse.github.io/baobab/v/
its the branch development_calc which is used now

**Comment by brandonpille** [comment]
I'm going to add a yaml file that will push the documenation. It will only push on commits to development. It will generate the documentation before pushing it so that we don't have to add the documentation to the repo.
